-- AlterTable
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "gstEnabled" BOOLEAN NOT NULL DEFAULT true;

-- AlterTable
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "gstEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "defaultCgstRate" DECIMAL(5,2) NOT NULL DEFAULT 9;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "defaultSgstRate" DECIMAL(5,2) NOT NULL DEFAULT 9;
