import { Document, Image, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import type { CasualSwimBillDto } from "@/lib/casual-swim-bill";
import {
  buildCasualSwimReceiptBreakdown,
  CASUAL_SWIM_RECEIPT_WIDTH_MM,
  formatReceiptLineItem,
  formatReceiptTimestamp,
  formatTicketNumberDisplay,
} from "@/lib/casual-swim-receipt-format";
import { formatCurrency } from "@/lib/utils";

const RECEIPT_WIDTH_PT = CASUAL_SWIM_RECEIPT_WIDTH_MM * 2.83465; // mm → pt

const styles = StyleSheet.create({
  page: {
    width: RECEIPT_WIDTH_PT,
    paddingHorizontal: 8,
    paddingVertical: 8,
    fontSize: 7.5,
    fontFamily: "Helvetica",
    color: "#111",
  },
  center: { textAlign: "center", alignItems: "center" },
  logo: { width: 52, height: 52, objectFit: "contain", marginBottom: 4, alignSelf: "center" },
  title: { fontSize: 10, fontWeight: 700, textAlign: "center" },
  subtitle: { fontSize: 7, textAlign: "center", marginBottom: 4, color: "#444" },
  ticketNo: {
    fontSize: 11,
    fontWeight: 700,
    textAlign: "center",
    marginBottom: 4,
    letterSpacing: 0.5,
  },
  divider: { borderBottomWidth: 1, borderBottomColor: "#ccc", marginVertical: 4 },
  row: { flexDirection: "row", justifyContent: "space-between", marginBottom: 1 },
  meta: { fontSize: 7, color: "#333" },
  sectionTitle: { fontSize: 7, fontWeight: 700, marginTop: 2, marginBottom: 2 },
  lineItem: { fontSize: 7, marginBottom: 1 },
  subtotal: { fontSize: 7, fontWeight: 600, marginTop: 2, marginBottom: 2 },
  total: { fontSize: 12, fontWeight: 700, textAlign: "center", marginVertical: 4 },
  footer: { fontSize: 7, textAlign: "center", marginTop: 2, color: "#444" },
  footerBold: { fontSize: 7, textAlign: "center", fontWeight: 600 },
});

function metaRow(label: string, value: string) {
  return (
    <View style={styles.row}>
      <Text style={styles.meta}>{label}</Text>
      <Text style={styles.meta}>{value}</Text>
    </View>
  );
}

export function CasualSwimReceiptPDF({
  bill,
  logoSrc,
}: {
  bill: CasualSwimBillDto;
  logoSrc: string;
}) {
  const created = formatReceiptTimestamp(new Date(bill.createdAt));
  const printed = formatReceiptTimestamp(new Date());
  const { swimmingLines, rentalLines } = buildCasualSwimReceiptBreakdown(bill);

  return (
    <Document>
      <Page size={[RECEIPT_WIDTH_PT, 720]} style={styles.page}>
        <View style={styles.center}>
          <Image src={logoSrc} style={styles.logo} />
          <Text style={styles.title}>MR Academy</Text>
          <Text style={styles.subtitle}>Swimming Pool & Spa</Text>
        </View>

        <View style={styles.divider} />
        <Text style={styles.ticketNo}>{formatTicketNumberDisplay(bill.ticketNumber)}</Text>
        {metaRow("Date", created.date)}
        {metaRow("Time", created.time)}
        {metaRow("Cashier", bill.createdBy)}

        {swimmingLines.length > 0 && (
          <>
            <View style={styles.divider} />
            <Text style={styles.sectionTitle}>SWIMMING</Text>
            {swimmingLines.map((line) => (
              <Text key={line.label} style={styles.lineItem}>
                {formatReceiptLineItem(line)}
              </Text>
            ))}
            <Text style={styles.subtotal}>
              Swimming Total = {formatCurrency(bill.swimmingAmount)}
            </Text>
          </>
        )}

        {rentalLines.length > 0 && (
          <>
            <View style={styles.divider} />
            <Text style={styles.sectionTitle}>RENTAL</Text>
            {rentalLines.map((line) => (
              <Text key={line.label} style={styles.lineItem}>
                {formatReceiptLineItem(line)}
              </Text>
            ))}
            <Text style={styles.subtotal}>Rental Total = {formatCurrency(bill.rentalAmount)}</Text>
          </>
        )}

        <View style={styles.divider} />
        <Text style={styles.total}>TOTAL {formatCurrency(bill.totalAmount)}</Text>

        <View style={styles.divider} />
        <Text style={styles.meta}>Printed At:</Text>
        <Text style={styles.meta}>{printed.date}</Text>
        <Text style={styles.meta}>{printed.time}</Text>

        <View style={styles.divider} />
        <Text style={styles.footerBold}>Thank You</Text>
        <Text style={styles.footer}>MR Academy Swimming Pool & Spa</Text>
        <Text style={styles.footer}>Generated By: {bill.createdByUsername}</Text>
      </Page>
    </Document>
  );
}
