import { Document, Image, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import type { CasualSwimBillDto } from "@/lib/casual-swim-bill";
import {
  buildCasualSwimReceiptBreakdown,
  formatReceiptLineItem,
  formatReceiptTimestamp,
  formatTicketNumberDisplay,
} from "@/lib/casual-swim-receipt-format";
import {
  CASUAL_SWIM_RECEIPT_PDF_WIDTH_PT,
  estimateCasualSwimReceiptPdfHeightPt,
} from "@/lib/casual-swim-receipt-pdf-size";
import { formatCurrency } from "@/lib/utils";
import { getCasualSwimReceiptPaymentLines } from "@/lib/casual-swim-payment";

const styles = StyleSheet.create({
  page: {
    width: CASUAL_SWIM_RECEIPT_PDF_WIDTH_PT,
    paddingHorizontal: 8,
    paddingVertical: 8,
    fontSize: 8,
    fontFamily: "Helvetica",
    color: "#111",
  },
  center: { textAlign: "center", alignItems: "center" },
  logo: { width: 46, height: 46, objectFit: "contain", marginBottom: 2, alignSelf: "center" },
  title: { fontSize: 10, fontWeight: 700, textAlign: "center" },
  subtitle: { fontSize: 7, textAlign: "center", marginBottom: 2, color: "#444" },
  ticketNo: {
    fontSize: 11,
    fontWeight: 700,
    textAlign: "center",
    marginVertical: 3,
    letterSpacing: 0.5,
  },
  divider: { borderBottomWidth: 1, borderBottomColor: "#bbb", marginVertical: 4 },
  dividerStrong: { borderBottomWidth: 1.5, borderBottomColor: "#111", marginVertical: 4 },
  row: { flexDirection: "row", justifyContent: "space-between", marginBottom: 1 },
  meta: { fontSize: 7.5, color: "#222" },
  sectionTitle: { fontSize: 7.5, fontWeight: 700, marginBottom: 2, letterSpacing: 0.3 },
  lineItem: { fontSize: 7.5, marginBottom: 1 },
  subtotal: { fontSize: 7.5, fontWeight: 600, marginTop: 1, marginBottom: 1 },
  total: { fontSize: 14, fontWeight: 700, textAlign: "center", marginVertical: 3 },
  footer: { fontSize: 7.5, textAlign: "center", color: "#444" },
  footerBold: { fontSize: 7.5, textAlign: "center", fontWeight: 600 },
  footerBlock: { alignItems: "center", marginTop: 2 },
});

function metaRow(label: string, value: string) {
  return (
    <View style={styles.row}>
      <Text style={styles.meta}>{label}</Text>
      <Text style={styles.meta}>{value}</Text>
    </View>
  );
}

export type ReceiptPdfDocumentProps = {
  bill: CasualSwimBillDto;
  logoSrc: string;
};

/**
 * Dedicated thermal receipt PDF — receipt fields only, single page.
 */
export function ReceiptPdfDocument({ bill, logoSrc }: ReceiptPdfDocumentProps) {
  const created = formatReceiptTimestamp(new Date(bill.createdAt));
  const { swimmingLines, rentalLines } = buildCasualSwimReceiptBreakdown(bill);
  const payment = getCasualSwimReceiptPaymentLines(bill);
  const pageHeightPt = estimateCasualSwimReceiptPdfHeightPt(bill);

  return (
    <Document>
      <Page size={[CASUAL_SWIM_RECEIPT_PDF_WIDTH_PT, pageHeightPt]} style={styles.page} wrap={false}>
        <View style={styles.center}>
          <Image src={logoSrc} style={styles.logo} />
          <Text style={styles.title}>MR Academy</Text>
          <Text style={styles.subtitle}>Swimming Pool & Spa</Text>
        </View>

        <View style={styles.divider} />

        <Text style={styles.ticketNo}>{formatTicketNumberDisplay(bill.ticketNumber)}</Text>
        {metaRow("Date", created.date)}
        {metaRow("Time", created.time)}
        {metaRow("Cashier", bill.createdBy)}
        {metaRow("Payment Mode", payment.mode)}
        {payment.lines.map((line) => metaRow(line.label, formatCurrency(line.amount)))}

        {swimmingLines.length > 0 && (
          <>
            <View style={styles.divider} />
            <Text style={styles.sectionTitle}>SWIMMING</Text>
            {swimmingLines.map((line) => (
              <Text key={line.label} style={styles.lineItem}>
                {formatReceiptLineItem(line)}
              </Text>
            ))}
            <Text style={styles.subtotal}>
              Swimming Total = {formatCurrency(bill.swimmingAmount)}
            </Text>
          </>
        )}

        {rentalLines.length > 0 && (
          <>
            <View style={styles.divider} />
            <Text style={styles.sectionTitle}>RENTAL</Text>
            {rentalLines.map((line) => (
              <Text key={line.label} style={styles.lineItem}>
                {formatReceiptLineItem(line)}
              </Text>
            ))}
            <Text style={styles.subtotal}>Rental Total = {formatCurrency(bill.rentalAmount)}</Text>
          </>
        )}

        <View style={styles.dividerStrong} />
        <Text style={styles.total}>TOTAL {formatCurrency(bill.totalAmount)}</Text>
        <View style={styles.dividerStrong} />

        <View style={styles.footerBlock}>
          <Text style={styles.footerBold}>Thank You</Text>
          <Text style={styles.footer}>MR Academy Swimming Pool & Spa</Text>
          <Text style={styles.footer}>Generated By: {bill.createdByUsername}</Text>
        </View>
      </Page>
    </Document>
  );
}
